[ADD]project_diary: New module created
avanzosc/project-addons pull request #109
Opened 2018-12-18 11:51 UTC by gontzalgm

2018-12-18 13:35 UTC, oihane commented
@avanzosc/developers review, please

2018-12-18 13:58 UTC, anajuaristi commented on project_diary/models/project_diary.py
> +    _inherit = 'project.project'
NO VALE
Tienes que crear un nuevo objeto project.history que tenga los campos que se piden y a este nuevo objeto meterle una relación many2one a project.

2018-12-18 13:58 UTC, anajuaristi commented on project_diary/views/project_diary_view.xml
> +                        <field name="project_id" invisible="True"/>
Incorrecto.
El nuevo objeto project_history debe tener sus propios form y tree. 
El tree se mostrará embebido en el formulario del proyecto

2018-12-18 13:58 UTC, anajuaristi commented on project_diary/views/project_diary_view.xml
> +</odoo>
:-1:  Hay que rehacerlo entero.
Por favor, pon foco en lo que se pide y si no se entiende pregunta.

2018-12-18 13:59 UTC, anajuaristi requested changes
Rehacer y volver a subir

2018-12-19 15:49 UTC, anajuaristi submitted a review, later dismissed

2018-12-19 15:49 UTC, anajuaristi commented on project_diary/models/project_diary.py
>      summ = fields.Text(string='Summary')
Llámale summary. Summ se puede confundir con suma y no es significativo.

2018-12-19 15:49 UTC, anajuaristi commented on project_diary/views/project_diary_view.xml
> +                <field name="summ" />
Summary

2018-12-19 15:49 UTC, anajuaristi commented on project_diary/views/project_diary_view.xml
> +              action="project_diary_form_view_action"/>
Un menu item no abre un form, sino un tree
Con poner project_diary_action vale

2018-12-19 15:49 UTC, anajuaristi commented on project_diary/views/project_diary_view.xml
> +                <field name="project_id" invisible="True"/>
Si haces el project_id invisible, cuando entres por el menú ¿como sabes a qué project pertenece el history?

2018-12-19 15:51 UTC, anajuaristi commented
Porfa, realiza los cambios solicitados y cuando esté, mergeadlo.
@oihane review please before merging
Gracias

2018-12-19 15:55 UTC, oihane requested changes
@anajuaristi cuando se desactiva un proyecto, desactivaria también su "diario"? y a la hora de copiar??

2018-12-19 15:55 UTC, oihane commented on project_diary/models/project_diary.py
> +    summ = fields.Text(string='Summary')
denomina el campo como summary

2018-12-19 15:55 UTC, oihane commented on project_diary/models/project_diary.py
> +    project_id = fields.Many2one(comodel_name='project.project')
Ponlo como requerido, y ondelete="cascade"

2018-12-19 15:55 UTC, oihane commented on project_diary/views/project_diary_view.xml
> +                <field name="project_id" invisible="True"/>
Mira en el modulo de viabilidad (por ejemplo) como hicimos para que pasando por contexto el 'hide_project_id' se ocultase o se mostrase, dado que si accedes directamente es necesario que se muestre.

2018-12-19 15:55 UTC, oihane commented on project_diary/views/project_diary_view.xml
> +                        <field name="project_id" invisible="True"/>
Lo mismo que en tree

2018-12-19 15:55 UTC, oihane commented on project_diary/views/project_diary_view.xml
> +    <record id="project_diary_form_view_action" model="ir.actions.act_window">
pon el id como "project_diary_action"

2018-12-19 15:55 UTC, oihane commented on project_diary/views/project_diary_view.xml
> +              name="Project Diary"
Como le estás añadiendo una acción no es necesario ponerle el name, coge el de la acción

2018-12-19 15:55 UTC, oihane commented on project_diary/views/project_project_view.xml
> +            <page name="settings" position="before">
en vez de "antes de los ajustes" ponlo dentro de notebook
```xml
<notebook position="inside">
```

2018-12-19 15:55 UTC, oihane commented on project_diary/views/project_project_view.xml
> +</odoo>
Falta salto de línea

2018-12-19 15:55 UTC, oihane commented on project_diary/views/project_diary_view.xml
> +    </record>
acuerdate de añadir el contexto, para ocultar el proyecto cuando es preciso.

2018-12-19 15:55 UTC, oihane commented on project_diary/security/ir.model.access.csv
> +access_project_diary,access_project_diary,model_project_diary,base.group_user,1,0,0,0
Tienes que añadir permisos para todo a algun grupo, en este caso sería el usuario de proyecto, si no solo el usuario de id=1 podrá meter datos.

2018-12-20 11:16 UTC, oihane commented on project_diary/views/project_project_view.xml
> +    <record model="ir.ui.view" id="project_diary_form_view">
Cambia el id, porque lo estás duplicando

2018-12-21 09:35 UTC, oihane approved these changes
LGTM

2018-12-21 09:41 UTC, Daniel-CA approved these changes

2018-12-21 09:56 UTC, merged