12.0 mig project task cost
avanzosc/project-addons pull request #215
Opened 2020-05-16 08:07 UTC by alfredoavanzosc

2020-05-19 07:03 UTC, alfredoavanzosc commented
@avanzosc/developers ... review please.

2020-05-19 13:48 UTC, oihane commented
@alfredoavanzosc porque separas la ejecución del modulo?

2020-05-21 12:48 UTC, alfredoavanzosc commented
> @alfredoavanzosc porque separas la ejecución del modulo?

Porque se hace incompatible con el test del módulo "account_analytic_billing_plan". El caso es que al instalar "project_task_cost", al objeto "producto" le mete un campo de tipo char, o text, no me acuerdo bien, que es obligatorio. Entonces cuando se va a ejecutar el test del módulo "account_analytic_billin_plan" peta su test porque no se está informando de este campo.
Este es el motivo por el que he separado los test.

2020-05-21 16:05 UTC, oihane requested changes

2020-05-21 16:05 UTC, oihane commented on project_task_cost/README.rst
> +  for coordinator users, a new group above project manager.
No es necesario cambiar el README sobretodo porque el texto sigue siendo el mismo y no estás realizando ningún listado

2020-05-21 16:08 UTC, oihane commented on project_task_cost/tests/test_project_task_cost.py
> +class TestProjectTaskCost(common.SavepointCase):
Prueba a añadir lo siguiente antes del class

```python
@common.at_install(False)
@common.post_install(True)
```

El problema del billing.plan es que este modulo instala el modulo sale.

2020-05-22 09:26 UTC, closed without merging