[IMP] project_task_meeting: Solve an agrupation of tasks in meetings.
avanzosc/project-addons pull request #236
Opened 2021-06-30 14:03 UTC by Berezi

2021-06-30 14:04 UTC, Berezi commented
@anajuaristi @oihane @Daniel-CA @alfredoavanzosc review please.

2021-06-30 14:49 UTC, oihane requested changes

2021-06-30 14:49 UTC, oihane commented on project_task_meeting/models/calendar_event.py
> +        result = result | {'task_id'}
```python
result |= {"task_id"}
```

2021-07-01 08:21 UTC, Berezi commented on project_task_meeting/models/calendar_event.py
> +        result = result | {'task_id'}
Aldaketa egina. Eskerrik asko.

2021-07-06 09:22 UTC, anajuaristi approved these changes

2021-07-06 09:28 UTC, merged